name: HTML5ChatMC
version: '${version}'
main: com.github.karlkm.html5chatmc.HTML5ChatMC
api-version: '1.20'
authors: [karl-k-m]
description: A Paper plugin for piping HTML5Chat messages into Minecraft chat.
website: https://github.com/karl-k-m
commands:
  html5:
    description: Toggle html5chat integration on and off.
    usage: /html5
  html5toggle:
    description: Toggle html5chat integration on and off.
    usage: /html5toggle